/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'jge' at '9/18/15 11:10 AM' with Gradle 2.4
 *
 * @author jge, @date 9/18/15 11:10 AM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
